// Standalone HTML deliberately bypasses the app layout, analytics, auth SDK and PWA scripts.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
import { createHash } from 'node:crypto';
import { NextRequest, NextResponse } from 'next/server';
import { PREPARER_HEADERS } from '@/lib/preparer/http';

export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id)) return new NextResponse('Link unavailable.', { status: 404, headers: PREPARER_HEADERS });
  const script = `(()=>{const token=new URLSearchParams(location.hash.slice(1)).get('token');history.replaceState(null,'',location.pathname);const button=document.getElementById('download'),status=document.getElementById('status');if(!token){status.textContent='Open the complete private link supplied by the owner.';button.disabled=true;return;}button.addEventListener('click',async()=>{button.disabled=true;status.textContent='Checking the private link…';try{const response=await fetch('/api/preparer-handoffs/download',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:${JSON.stringify(id)},token})});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||'The package is unavailable. Ask the owner for a new link.');}const blob=await response.blob();const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=(response.headers.get('Content-Disposition')||'').match(/filename="([a-z0-9.-]+)"/)?.[1]||'writeoff-preparer-package.zip';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(href);const issues=Number(response.headers.get('X-Receipt-Issues')||0);status.textContent='Downloaded. '+(issues?issues+' receipt issue(s) need review. ':'')+'Read manifest.json and unresolved-questions.json before using the records.';}catch(error){status.textContent=error instanceof Error?error.message:'Download failed. Please retry.';}finally{button.disabled=false;}});})();`;
  const hash = createHash('sha256').update(script).digest('base64');
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="robots" content="noindex,nofollow,noarchive"><title>Private preparer package | WriteOff</title><style>body{font-family:system-ui,sans-serif;background:#f5f6f8;color:#172039;margin:0;padding:40px 20px}main{max-width:480px;margin:8vh auto;background:white;border:1px solid #dde2eb;border-radius:24px;padding:28px}h1{font-size:26px;letter-spacing:-.7px}p{line-height:1.6}small{color:#526078}button{background:#245ff3;color:white;padding:14px 22px;border:0;border-radius:12px;font:inherit;font-weight:600;cursor:pointer}button:disabled{opacity:.5;cursor:wait}#status{font-size:14px;min-height:48px}</style></head><body><main><small>WriteOff · Private handoff</small><h1>Your preparer package</h1><p>Download a fixed snapshot of records and original receipts the owner chose to share.</p><button id="download" type="button">Download package</button><p id="status" role="status" aria-live="polite">This link expires and can be revoked by the owner.</p><small>This download does not grant account access or file a tax return. Keep these personal records secure. Review the receipt manifest and unresolved questions included in the ZIP.</small><noscript><p>Enable JavaScript to open this private download. The access token is kept out of request URLs.</p></noscript></main><script>${script}</script></body></html>`;
  return new NextResponse(html, { headers: { ...PREPARER_HEADERS, 'Content-Type': 'text/html; charset=utf-8',
    'Content-Security-Policy': `default-src 'none'; script-src 'sha256-${hash}'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'` } });
}
